import {
  Anonymous_Pro,
  Kiwi_Maru,
  Zen_Maru_Gothic,
  Zen_Kurenaido,
} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anonymousPro = Anonymous_Pro({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
  variable: "--font-anonymous-pro",
  display: "swap",
});

const kiwiMaru = Kiwi_Maru({
  subsets: ["latin"],
  style: "normal",
  weight: ["300", "400", "500"],
  variable: "--font-kiwi-maru",
  display: "swap",
});

const zenMaruGothic = Zen_Maru_Gothic({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
  variable: "--font-zen-maru-gothic",
  display: "swap",
});

// Use catch-copy
const zenKurenaido = Zen_Kurenaido({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
  variable: "--font-zen-kurenaido",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${anonymousPro.variable} ${kiwiMaru.variable} ${zenMaruGothic.variable} ${zenKurenaido.variable} ${harenosora.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
